sudo: required

dist: xenial

language: elixir

elixir:
  - 1.7.2

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

env:
  global:
    - PGPORT=5433
    - MIX_ENV=test
    
script:
  - mix test
