language: elixir

elixir:
  - 1.7.2

addons:
  postgresql: '10.5'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test
    
script:
  - mix test
